In [3]:
import numpy as np

In [6]:
def f(x,y):
    return 10*x+y

In [7]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [30]:
b[2:4,2:4]

array([[22, 23],
       [32, 33]])

In [16]:
b[::-1][1]

array([30, 31, 32, 33])

In [11]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [12]:
b[4]

array([40, 41, 42, 43])

In [13]:
b[-1]

array([40, 41, 42, 43])

In [35]:
for e in b.flat:
    print(e)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [36]:
b.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [46]:
b.reshape(-1)

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [96]:
b.resize(2,6)

In [78]:
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [85]:
a.sort()

In [86]:
a

array([[1., 5., 9., 9.],
       [3., 4., 4., 8.],
       [0., 5., 5., 7.]])

In [89]:
l=a[::-1]
l

array([[0., 5., 5., 7.],
       [3., 4., 4., 8.],
       [1., 5., 9., 9.]])

In [90]:
a

array([[1., 5., 9., 9.],
       [3., 4., 4., 8.],
       [0., 5., 5., 7.]])

In [93]:
np.savetxt("npdata.txt",a)

In [94]:
data=np.loadtxt("npdata.txt")
data

array([[1., 5., 9., 9.],
       [3., 4., 4., 8.],
       [0., 5., 5., 7.]])

In [95]:
a

array([[1., 5., 9., 9.],
       [3., 4., 4., 8.],
       [0., 5., 5., 7.]])