In [2]:
import torch

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_()

tensor([0., 1., 2., 3.], requires_grad=True)

In [5]:
x.grad

In [6]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward()

In [8]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [9]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [10]:
4*x

tensor([ 0.,  4.,  8., 12.], grad_fn=<MulBackward0>)

In [11]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [24]:
x.grad.zero_()
y = x * x
u = y.detach() # detach y into u. now u is a constant
z = u * x

z.sum().backward()
x.grad, u

(tensor([0., 1., 4., 9.]), tensor([0., 1., 4., 9.]))