In [218]:
import torch

In [219]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [220]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [221]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [222]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [223]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [224]:
X.shape

torch.Size([3, 4])

In [225]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [226]:
X[1,2]

tensor(6.)

In [227]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [228]:
X[:2,1:3]

tensor([[1., 2.],
        [5., 6.]])

In [229]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [230]:
x[0:3:2]

tensor([0., 2.])

In [231]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [232]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [233]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [234]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [235]:
G = (X == Y)
G

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [236]:
G.sum()

tensor(2)

In [237]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [238]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [239]:
A = x.numpy()
A

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)

In [240]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [241]:
torch.logical_or(X < Y, X > Y)

tensor([[ True, False,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [242]:
X.T

tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])

In [243]:
X.sum(axis=0)

tensor([12., 15., 18., 21.])

In [244]:
X.sum(axis=0)

tensor([12., 15., 18., 21.])

In [245]:
X.shape

torch.Size([3, 4])

In [246]:
len(X)

3

In [247]:
A

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)

In [248]:
R = torch.randn((2,3,4))
R

tensor([[[-0.0624, -0.7839,  1.1745, -1.7706],
         [-0.6188,  0.4339, -0.5987,  0.5889],
         [ 0.1091,  2.1487,  1.1846, -0.8574]],

        [[ 0.6625, -0.1762, -1.1845,  0.5049],
         [-0.3919,  1.3721,  1.6357, -0.7150],
         [ 0.3269, -1.1937,  0.0693,  0.7254]]])

In [249]:
R.sum(axis=0).shape

torch.Size([3, 4])

In [250]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [251]:
X.shape

torch.Size([3, 4])

In [252]:
X.sum(axis=0)

tensor([12., 15., 18., 21.])

In [253]:
X.sum(axis=0).shape

torch.Size([4])

In [254]:
import numpy as np
arr = np.array([2,2])
t = torch.from_numpy(arr)

In [255]:
t.device

device(type='cpu')