In [38]:
import torch

**Training**

In [39]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
z.shape, y.shape # probabilities for each training sample

(torch.Size([3]), torch.Size([3]))

In [40]:
z, y

(tensor([-3.1701, -0.5742,  4.1835], grad_fn=<AddBackward0>),
 tensor([0., 0., 0.]))

In [41]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss

tensor(1.5622, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [42]:
loss.backward()

In [43]:
w.grad, b.grad

(tensor([[0.0134, 0.1201, 0.3283],
         [0.0134, 0.1201, 0.3283],
         [0.0134, 0.1201, 0.3283],
         [0.0134, 0.1201, 0.3283],
         [0.0134, 0.1201, 0.3283]]),
 tensor([0.0134, 0.1201, 0.3283]))

In [44]:
z.grad # need retain_grad()

C:\Users\abhin\AppData\Local\Temp\ipykernel_192\1991036887.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  z.grad # need retain_grad()


In [45]:
z.grad_fn

**Inference**

In [ ]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad(): # no grad to disable it
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


**Or detach it to disable grad tracking**

In [51]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False
